### ISSUE TITLE
Should get_type_hints be added to the Signature class?

### ISSUE THREAD

**Issue by JimJJewett** [ambv/typehinting#100]

**Comment by gvanrossum** [comment]
What?

**Comment by JimJJewett** [comment]
inspect.Signature.parameters returns the parameters with their annotations, but those annotations are as-written.

get_type_hints() will return the annotations dictionary, except that strings are replaced by the objects they represent.  This would often be a useful thing to do from a Signature object as well.

**Comment by gvanrossum** [comment]
Yeah, but we can't change inspect.py for earlier Python versions, and Signature was added in 3.3 -- but typing.py supports 3.2 and up.

**Comment by JimJJewett** [comment]
Even if the implementation is in typing (or duplicated), I think the API should be available from Signature objects ... if this normalization is standard, then it is reasonably to want this normalization from Signature, even if you aren't otherwise deep into typing.

**Comment by gvanrossum** [comment]
We'll leave that to 3.6, okay?

**Comment by JimJJewett** [comment]
Are you leaving it to 3.6 because you aren't sure it is a good idea, because you aren't sure the API won't change (typing is provisional, Signature isn't), or just as a matter of time?

As in, would a patch make a difference?

**Comment by gvanrossum** [comment]
I honestly don't see any reason to add it to Signature.
