### ISSUE TITLE
Give an example of runtime usage for Design By Contract

### ISSUE THREAD

**Issue by JimJJewett** [ambv/typehinting#101]
https://github.com/ceronman/typeannotations 
may be an appropriate reference.  I'm not sure how active it is, or how well it meshes with the exact PEP, (it seems to have more focus on structural typing) but it is an example of run-time use of type hinting that could/should benefit from a standardized vocabulary and conventions.

**Comment by gvanrossum** [comment]
Is there a reason this needs to be referenced in the PEP? Perhaps it would fit better in PEP 482 (literature overview)?

**Comment by JimJJewett** [comment]
482 would probably be a better place, but for one caveat:  the PEP seems to suggest that there is no run-time usage of type hinting.  While run-time usage may not be as common or mature as static typing, it does exist, and pointing to one example (even if only to say "not fully supported in this version") would be a way to do that.

**Comment by gvanrossum** [comment]
If you search the PEP text for "runtime" you'll find plenty of mention. And I want to send a m,uch stronger message than "not fully supported in this version" -- I think it's rarely if ever going to be a good idea. And the PEP is pretty clear about that already.
