### ISSUE TITLE
Any is useless

### ISSUE THREAD

**Issue by kirbyfan64** [ambv/typehinting#102]
Why not just use `object` instead? Watch:

```
ryan@DevPC-LX:~$ ipython3
Python 3.4.1 |Anaconda 2.1.0 (64-bit)| (default, Sep 10 2014, 17:10:18) 
Type "copyright", "credits" or "license" for more information.

IPython 2.2.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: isinstance(1, object)
Out[1]: True

In [2]: isinstance('sasd', object)
Out[2]: True

In [3]: class X(): pass

In [4]: isinstance(X(), object)
Out[4]: True

In [5]: isinstance(X, object)
Out[5]: True

In [6]: isinstance(None, object)
Out[6]: True

In [7]: isinstance(type(None), object)
Out[7]: True

In [8]: issubclass(X, object)
Out[8]: True

In [9]: issubclass(type(None), object)
Out[9]: True

In [10]: 
```

*Everything* seems to be a subclass of `object`. Why not get rid of `Any`? They would end up being almost the same thing.

**Comment by rockneurotiko** [comment]
Actually object and Any are almost the same, but the difference is essential.

Like @gvanrossum explained in his talk in PyCon 2015 (https://www.youtube.com/watch?v=2wDvzy6Hgxg) [20:38 Any exlanation], Any is the top and the bottom of the class tree, while object is only the top.

**Comment by kirbyfan64** [comment]
@rockneurotiko But, in the context of a static type checker like here, where `Any` is mostly just used for type signatures, would that matter?

**Comment by rockneurotiko** [comment]
@kirbyfan64 Of course, if you don't have Any as the bottom, you won't have Gradual typing, because if you are checking the types, and don't declare, it will be Any.

For example, here I show that if you declare a variable as Any, it will typecheck against the argument and the return type (because Any is top and bottom) but an object type does not typecheck (here is a variable for simplicity, but you can apply to any example where you have a type, for example a return type).

(In the comments where mypy complains)

``` python
from typing import Any

class A:
    pass

class B(A):
    pass

class C:
    pass

def testAny(var: A) -> A:
    return var

testvar = B()
testAny(testvar)

testvarany = C()  # type: Any
testAny(testvarany)

testvarobj = C()  # type: object
testAny(testvarobj)  # Argument 1 to "testAny" has incompatible type "object"; expected "A"

testnotany = C()
testAny(testnotany)  # Argument 1 to "testAny" has incompatible type "C"; expected "A"
```
