### ISSUE TITLE
TypeVar name repetition

### ISSUE THREAD

**Issue by JimJJewett** [ambv/typehinting#103]
X = TypeVar('X', ...) is redundant, because variables don't have access to their own name.

There is (at least in an issue, if not in the PEP) concern over what to do if they don't match, e.g.
X = TypeVar('Y', ...)

Two of the simplifying-metaclasses proposals deals with this pattern.  

If one of them gets in as quickly as this PEP, it would be nice to see this fixed, or at least fixable in a future python.

**Comment by kirbyfan64** [comment]
Crazy idea: what about:

```python3
class X(TypeVar): pass
...
```

**Comment by gvanrossum** [comment]
The type checker will complain if the names don't match. The class hack is not an improvement, and it would be problematic to extend it with various arguments to TypeVar.

What are the simplifying-metaclasses proposals you are referring to?

**Comment by JimJJewett** [comment]
PEP 487 and PJE's request to unwithdraw PEP 422

**Comment by gvanrossum** [comment]
But do those PEPs do anything about the global namespace? Also I'm not holding my breath that either one is accepted (nobody has asked me for a review yet). We'll cross that bridge when we get there, but for now we'll need to keep the current syntax to be compatible with 3.2 and up.
