### ISSUE TITLE
Mark postponed issues with a label to make them easier to ignore?

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#106]
Currently the decisions on some of the open issues seem to have been postponed until after Python 3.5. Maybe we should create an issue label for postponed issues to make it easier to see which issues are still unresolved.

Potential postponed issues:

* https://github.com/ambv/typehinting/issues/72
* https://github.com/ambv/typehinting/issues/28
* #7

**Comment by gvanrossum** [comment]
Good idea. Done.
