### ISSUE TITLE
Cannot subclass List[int]

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#113]
The PEP implies that this code should be valid:

```python
from typing import List

class MyList(List[int]): pass

x = MyList()
x.append(1)
```

However, this fails:

```
>>> x = MyList()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jukka/project/typehinting/prototyping/typing.py", line 1437, in __new__
    raise TypeError("Type List cannot be instantiated; use list() instead")
TypeError: Type List cannot be instantiated; use list() instead
```

(This was originally reported by @JamesGuthrie: https://github.com/JukkaL/mypy/issues/688)

Quote from the PEP draft:

```
``Generic[T]`` is only valid as a base class -- it's not a proper type.
However, user-defined generic types such as ``LinkedList[T]`` from the
above example and built-in generic types and ABCs such as ``List[T]``
and ``Iterable[T]`` are valid both as types and as base classes. For
example, we can define a subclass of ``Dict`` that specializes type
arguments::

  from typing import Dict, List, Optional

  class Node:
      ...

  class SymbolTable(Dict[str, List[Node]]):
      def push(self, name: str, node: Node) -> None:
          self.setdefault(name, []).append(node)

      def pop(self, name: str) -> Node:
          return self[name].pop()

      def lookup(self, name: str) -> Optional[Node]:
          nodes = self.get(name)
          if nodes:
              return nodes[-1]
          return None

``SymbolTable`` is a subclass of ``dict`` and a subtype of ``Dict[str,
List[Node]]``.
```

**Comment by gvanrossum** [comment]
Oh dang. I guess the prevention on instantiation should only apply to exactly List (etc.) not to subclasses.

**Comment by JukkaL** [comment]
I think that for consistency, we should also support subclassing `Tuple[...]`. Mypy used to support it (though it's currently broken: https://github.com/JukkaL/mypy/issues/279).

**Comment by gvanrossum** [comment]
I think subclassing `Tuple` or `Tuple[...]` is too complex to implement in typing.py (Tuple is not a generic class but a special construct, like Union or Callable), and I think tuple is not commonly subclassed (except via NamedTuple, which we've got covered). If you disagree, can you open a separate issue "allow subclassing Tuple[...]" and label it as "enhancement"?
