### ISSUE TITLE
Should non-type forward refences be prohibited?

### ISSUE THREAD

**Issue by ilevkivskyi** [ambv/typehinting#114]
Currently, `_eval_type(Tuple['42'],{},{})` evaluates to `Tuple[42]` - something that has not much sense. Should such behavior be prohibited? PEP currently says "Moreover, the expression should be parseable as a valid type hint".

This could be done by replacing `eval(self.__forward_code__, globalns, localns)` with `_type_check(eval(self.__forward_code__, globalns, localns), 'Forward references must evaluate to types.')`

**Comment by gvanrossum** [comment]
Thanks for the report and the suggested fix!
