### ISSUE TITLE
Small typo in the PEP

### ISSUE THREAD

**Issue by avassalotti** [ambv/typehinting#116]
> The string literal should contain a valid Python expression (i.e.,
> ``compile(lit, '', 'expr')`` should be a valid code object) [...]

compile(lit, 'expr') doesn't work AFAIK. I think this is intended to be compile(lit, 'eval').

**Comment by gvanrossum** [comment]
Thanks for the report! Fixed (in GitHub -- I'm just collecting fixes there for now.)
