### ISSUE TITLE
Should generic metaclasses be allowed?

### ISSUE THREAD

**Issue by ilevkivskyi** [ambv/typehinting#120]
Currently it is not clear from PEP whether it is allowed to write (regardless that it is weird):
```python
class MyMeta(type, Generic[T]):
    ...
```
If I do so with the current version of typing.py then
```python
isinstance(whatever, MyMeta)
``` 
raises 
```python
TypeError: __subclasscheck__() takes exactly one argument (0 given)
```
The reason is that `type.__subclasscheck__` is different form `object.__subclasscheck__`.
Similar things happen for `issubclass` and also when I use `MyMeta[t]` or `MyMeta[T]`.
Is this a bug or generic metaclasses should be prohibited/discouraged?

**Comment by gvanrossum** [comment]
This probably can't be made to work right, for the reason you found. What would it mean anyway? Or are you just suggesting that I add a line to the PEP explaining this is not supported?

**Comment by ilevkivskyi** [comment]
Yes, exactly, it is better to explain that it is not supported.
