### ISSUE TITLE
Maybe we shouldn't specify details of type inference

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#121]
I wouldn't like to specify the inferred type as `Node[Any]` in the extract below:

> Now there are three ways we can instantiate this class; the type
> inferred by a type checker will be different depending on the form we
> use:
>
> * ``x = Node()`` -- the type inferred for x is ``Node[Any]``.

I think that there are at least 3 reasonable ways to deal with the above code, depending on the context and the goals of a type checker. To make this slightly more interesting, assume that the type is called `LinkedList` instead of `Node`:

1. `Node[Any]` (as defined currently in the PEP)
2. Reject the code and require a type annotation (e.g., `x = None()  # type: Node[int]`), at least if the definition in within a statically typed function.
3. Look at the surrounding code and try to infer a precise type based on mutation operations. For example, if there is a `x.append(1)` nearby, we may be able to infer the type of `x` as `Node[int]` (assuming `append()` does what its name implies).

Mypy currently does (2), but I'm planning to eventually implement (3) for many common scenarios. Also, for module-level definitions mypy will switch to (1).

The rationale for using (1) for module-level definitions is that we don't want to reject dynamically typed modules, so we'll fall back to an imprecise type if we can't infer a precise type.

If we'd use (1) within statically typed functions, it would be easy to accidentally write imprecisely typed code that looks fully statically typed under casual inspection. (2) fixes that. Also, if mypy will actually use (3) (i.e., do a best-effort type inference for such code), then falling back to `Node[Any]` is even more problematic, as this would depend on the implementation details of the type inference algorithm, and it shouldn't be required for most programmers to understand the ins and outs of type inference.

**Comment by vlasovskikh** [comment]
I agree, maybe the PEP shouldn't specify these details.

Some checkers might want to do (1) while others (2). For example, (1) makes sense in an IDE where the user doesn't expect the IDE to force him/her to modify the code just to get rid of the warnings. (2) is more appropriate for a stand-alone checker that is run in a batch mode to find all possible problems.

**Comment by gvanrossum** [comment]
OK. Jukka, can you update the PEP?

**Comment by JukkaL** [comment]
Ok!



—
