### ISSUE TITLE
Type variables vs. overloads

### ISSUE THREAD

**Issue by The-Compiler** [ambv/typehinting#122]
One last thing I noticed while reading the PEP:

I had a hard time at grasping generics and what a `TypeVar` is, but the `AnyStr` example made it clear... or so I thought. I got confused again when I read the section about overloads:

> This description is more precise than would be possible using unions
(which cannot express the relationship between the argument and return
types)::
>
> [...]

Suppose we have something like:

```python
class Foo:
    ...
    @overload
    def bar(self, i: int) -> int: ...
    @overload
    def bar(self, s: str) -> str: ...
```

How is this different from this?

```python
IntStr = TypeVar('IntStr', int, str)

class Foo:
    def bar(self, i: IntStr) -> IntStr: ...
```

Are TypeVars just another way to write overloads in non-stub files?

I have the feeling there's more to it but I don't quite grasp it.

**Comment by JukkaL** [comment]
In the example you give, a type variable can be used instead of overloading. However, this is not always the case. Consider this example:

```
class Foo:
    ...
    @overload
    def bar(self, i: int) -> str: ...
    @overload
    def bar(self, s: str) -> float: ...
```

Now you can't use type variables to represent the type of the method.

**Comment by gvanrossum** [comment]
Jukka, can you try to clarify this a bit in the PEP, or at least explain things to Florian in this issue?

**Comment by JukkaL** [comment]
Ok!



—
