### ISSUE TITLE
Type of first argument of class methods should not be 'type'

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#123]
This is an extract from the PEP draft:

> An exception is that the first argument of instance and
> class methods does not need to be annotated; it is assumed to have the
> type of the containing class for instance methods, and ``type`` for
> class methods.

If the type of first argument of a class method is `type`, it wouldn't be possible to access other class attributes or methods via the argument. Consider this code:

```
class A:
    n = 0

    @classmethod
    def f(cls) -> None:
        cls.n = 1   # Error?
```

This should probably be okay, but `type` does not have attribute `n`, so a type checker would have to reject the code if type of `cls` is `type`. A better type would be something like `Type[A]` mentioned in #107. Note that we don't necessarily need to support `Type[A]` for user code -- this type can be internal to the type checker, similar to callable types with `*args` etc. that can't be represented using the type syntax.

(Mypy currently uses `Any` for the first argument of class methods, but that's an implementation limitation that should be fixed.)

**Comment by ilevkivskyi** [comment]
I agree, `Type[A]` would be much better. To implement this, one probably needs to also infer _values_ of variables for which type `type` is inferred. Then one can compare the inferred value with annotation `Type[A]`. By the way, currently mypy complains about this
```python
temp = dict

def f(x: dict):
    ...

mydict = temp()

f(mydict)
```
Actually, while I was typing this in Spyder (I am not sure but it uses pyflakes) it gave me a call signature for `dict` when I typed `temp(`

**Comment by ilevkivskyi** [comment]
Actually, if I replace `dict` with `int` then everything works as expected. Problem with `dict` probably was that it wants `Dict[A,B]`.

**Comment by ilevkivskyi** [comment]
Ok, may be it is not so easy. I just understood how huge is mypy. As a quick workaround maybe one can say that the type assumed for first arg in classmethod is `TypeVar('', bound=type)`?

**Comment by gvanrossum** [comment]
Jukka, can you update the PEP to say something vague about the `cls` argument to class methods? Without defining something like `Type[...]` -- we'll open that can of worms later.

**Comment by JukkaL** [comment]
Ok i'll do it later today. 



—
