### ISSUE TITLE
Bad covariance example

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#125]
This code example in the PEP draft is incorrect:

```
from typing import TypeVar

T = TypeVar('T', covariant=True)

class ImmutableList(Generic[T]):
    def append(self, T): ...
    ...
```

The argument should not be named `T`, and a covariant type variable should not be used as a method argument type (we probably don't want to append to an immutable list). A better example would be something like this:

```
from typing import TypeVar

T = TypeVar('T', covariant=True)

class ImmutableList(Generic[T]):
    def __getitem__(self, x: int) -> T: ...
    ...
```

**Comment by vlasovskikh** [comment]
+1

**Comment by gvanrossum** [comment]
Jukka, please fix this in the PEP.

**Comment by JukkaL** [comment]
Ok



—
