### ISSUE TITLE
Get rid of PY2, PY3, WINDOWS, POSIX

### ISSUE THREAD

**Issue by gvanrossum** [ambv/typehinting#128]
Mark Shannon really doesn't like these. They don't belong here and a type checker should recognize standard version checking code (e.g. using sys.version_info or six.PY3).

**Comment by JukkaL** [comment]
Yeah, they aren't really necessary. Maybe we could give examples of version checks that a type checker should recognize, since we can't expect all possible version checks to be recognized.

**Comment by markshannon** [comment]
How about the actual code from `typing.py` as examples and something along the lines of
"Checkers will attempt to infer the version and/or O/S being tested for, but don't expect them to understand `"".join(reversed(sys.platform)) == "xunil"`
