### ISSUE TITLE
Kill type comments

### ISSUE THREAD

**Issue by kislyuk** [ambv/typehinting#137]
I'm quite late to the party, and certainly understand that this is not the right time (and maybe not the right place) to raise this kind of architectural comment. But I think type comments are a poor architectural choice, and want to start a discussion about that.

Please let me know if this should be on the ML instead.

**Comment by gvanrossum** [comment]
The PEP was just accepted, with type comments in it. The reason to have them (despite the widely acknowledged problems) is that we don't have a reasonable alternative that will work with Python 3.4 too. You might want to start a discussion on python-ideas about what syntactic changes to Python 3.6 could be used to replace them.

**Comment by gvanrossum** [comment]
Let's only have issues for things we're going to fix in the relatively near future. We'll be living with type comments for a long time.
