### ISSUE TITLE
Release typing on PyPI

### ISSUE THREAD

**Issue by agronholm** [ambv/typehinting#138]
Currently, there is a nonfunctional package named "typing" on PyPI. It'd be great if the current code could be published there. I'm aware of backports.typing but that requires either a conditional import or adding the project as a requirement even on Python 3.5. There's also a problem with PyCharm not apparently recognizing backports.typing as the "authentic" type hints module so I'm getting errors like
`Expected 'Union[str, IResource]', got 'str' instead`.

**Comment by gvanrossum** [comment]
I have tried to get Łukasz's attention (he's got the keys for pushing new versions to PyPI) but he hasn't responded yet.

**Comment by vlasovskikh** [comment]
The related issue in the typing repo is https://github.com/JukkaL/typing/issues/46.

**Comment by agronholm** [comment]
Looks like there's typing-3.5.0b1 on PyPI now.
