### ISSUE TITLE
Should we adopt mypy's @overload?

### ISSUE THREAD

**Issue by gvanrossum** [ambv/typehinting#14]
In mypy there's an @overload decorator. However, it was introduced before Union, and the latter is usually sufficient (or using type variables).

Is it still needed? If we need it, should it be part of this PEP or should it be a separate proposal for a runtime feature to be added to functools (like @singledispatch)? But if separate, how would it interact with generic types?

**Comment by ambv** [comment]
The examples that @JukkaL listed here are one of the reasons pytypedecl went with a separate file for type definitions.

In general I saw some minor interest in having multiple dispatch implemented in functools after we introduced singledispatch. I'd be happy to work on that separate PEP as a follow-up.

Can we leave it out for now to not risk introducing a confusing feature that's impossible to remove later?

**Comment by gvanrossum** [comment]
We need *something* for stubs; there are a fair number of stdlib things
that are naturally expressed as overloads. (And then you have map() and
filter(), which are technically an overload of an infinite number of
different variants. But I'm okay with just listing 10 in the stub file.
This was discussed elsewhere, though I can't find it now.)

On Tue, Jan 6, 2015 at 11:41 PM, Łukasz Langa <notifications@github.com>
wrote:

> The examples that @JukkaL <https://github.com/JukkaL> listed here are one
> of the reasons pytypedecl went with a separate file for type definitions.
>
> In general I saw some minor interest in having multiple dispatch
> implemented in functools after we introduced singledispatch. I'd be happy
> to work on that separate PEP as a follow-up.
>
> Can we leave it out for now to not risk introducing a confusing feature
> that's impossible to remove later?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ambv/typehinting/issues/14#issuecomment-68988407>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by gvanrossum** [comment]
Closing .The decision is made. We'll support `@overload` in stubs only. The editing TODO is in README.rst. We'll also separately try to work on a PEP for multiple dispatch.
