### ISSUE TITLE
Variance of Mapping type

### ISSUE THREAD

**Issue by spkersten** [ambv/typehinting#140]
Currently, `Mapping` is defined to be covariant in its type for the key (`KT_co`). However, the key type is used as the type of a function argument (`__getitem__` and `get`) so it should be contravariant or invariant. Since `KT_co` is used as a return type as well, only invariant seems a valid option.

**Comment by gvanrossum** [comment]
Oops. I think you're right. Only the values should be covariant. I think
this means KT_co will be unused and and should be deleted.

**Comment by gvanrossum** [comment]
Can you double-check this before I copy it to two other repos?

**Comment by spkersten** [comment]
The commit looks good to me.
