### ISSUE TITLE
`SupportsAbs`, `SupportRound`, and `Reversible` could be covariant

### ISSUE THREAD

**Issue by spkersten** [ambv/typehinting#142]
I think that these classes can be covariant in there type variable instead of invariant: `SupportsAbs`, `SupportRound`, and `Reversible`.

**Comment by gvanrossum** [comment]
Why not the other Supports* classes? Do you haven an example where it matters? (Even if it's academic, an example would help me understand.)

**Comment by spkersten** [comment]
An example:

```python
class RationalNumber: pass
class NaturalNumber(RationalNumber): pass

def my_compare(a: RationalNumber, b: RationalNumber) -> bool:
    ...

def count_smaller(elements: Iterable[SupportsAbs[RationalNumber]], 
                  limit: SupportsAbs[RationalNumber]) -> int:
    ...
    if my_compare(abs(elements[i]), abs(elements[j])):
        ...
```

In this case `count_smaller` would work just as well on a `Iterable[SupportsAbs[NaturalNumber]]`, but for it to type check `Iterable[SupportsAbs[NaturalNumber]]` must be a subtype of `Iterable[SupportsAbs[RationalNumber]]` and therefore `SupportsAbs` covariant.

The other Supports* classes don't have a type variable, so this is not applicable.

**Comment by gvanrossum** [comment]
Yeah, you're right.
