### ISSUE TITLE
Should TypeVar's argument be an identifier?

### ISSUE THREAD

**Issue by ilevkivskyi** [ambv/typehinting#143]
Currently this works:
```
>>> t = TypeVar('$this is not even an identifier$')
>>> t
~$this is not even an identifier$
```
Maybe it should be prohibited by an additional check
```python
if not name.isidentifier():
    raise ValueError("TypeVar's argument must be an identifier")
```
in `TypeVar`'s `__new__`?

**Comment by gvanrossum** [comment]
I don't think that's a useful check. This is also wrong:
```
X = TypeVar('Y')
```
but we can't check for that at runtime. All these errors will be reported when you actually run the static checker.
