### ISSUE TITLE
Possibility to use type definition syntax in docstrings

### ISSUE THREAD

**Issue by germn** [ambv/typehinting#146]
PEP says we can use type definition syntax in annotations, comments, stub files. Why not to allow usage of this syntax in docstring? Some of IDE's already used their own type definition syntax in docstrings because it wasn't specified anywhere before ( https://www.jetbrains.com/pycharm/help/type-hinting-in-pycharm.html#d281633e18088 ): looks like now PEP gives us that syntax.

Instead of this:
http://i.imgur.com/jAEti51.png

we would be allowed to optionnaly write this:
http://i.imgur.com/S23ZzGY.png

This possibility has following advantages:
- Except of IDE's own defined type definition syntaxes for docstrings we will have single syntax, based of PEP
- It may be good alternative for anyone who don't like unreadable (in some cases) annotations ( http://aroberge.blogspot.ru/2015/01/type-hinting-in-python-focus-on.html )
- It doesn't have problems with backward compability and doesn't break PEP
- No additionnal work should be done: implementation of this option is on the IDE's side

Can this option be added in PEP?

**Comment by gvanrossum** [comment]
We considered that (and the advantages you mention aren't new to me) but we strongly prefer the approach currently advocated in the PEP. There are already several ways to get around the downsides, e.g. using stub files or stringified annotations. Adding more options will not help.
