### ISSUE TITLE
Add typing==3.5.0 and remove typing==0.0 from PyPI

### ISSUE THREAD

**Issue by vlasovskikh** [ambv/typehinting#148]
Currently running `pip install typing` will install `typing` version `0.0` which is essentially an empty package. Could you please remove this version in order to install `3.5.0b1` by default?

**Comment by vlasovskikh** [comment]
@ambv It seems that you are the owner of the package at PyPI :)

**Comment by vlasovskikh** [comment]
@ambv Please publish typing==3.5.0 from Python 3.5 at PyPI and delete typing==0.0.

**Comment by agronholm** [comment]
This needs a 3.5.0 final release now.

**Comment by ambv** [comment]
Sorry for the wait. Will push today and share maintainer privileges with @vlasovskikh, @gvanrossum and @JukkaL.

**Comment by agronholm** [comment]
There's still no new release. Anyone?

**Comment by ambv** [comment]
There's been some confusion about the state of the Python 2 backport for the release. I'm releasing it without it.

**Comment by agronholm** [comment]
Isn't that what backports.typing is for?

**Comment by agronholm** [comment]
So are we still waiting for something? There's still no new release on PyPI.

**Comment by vlasovskikh** [comment]
@ambv Got write access to the project on PyPI, thank you. Are you going to release 3.5.0 (without Python 2 support) or should I join and release it?

**Comment by gvanrossum** [comment]
At this point I think you should release it, and don't worry about Python 2
support.

On Thu, Oct 1, 2015 at 9:17 AM, Andrey Vlasovskikh <notifications@github.com
> wrote:

> @ambv <https://github.com/ambv> Got write access to the project on PyPI,
> thank you. Are you going to release 3.5.0 (without Python 2 support) or
> should I join and release it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ambv/typehinting/issues/148#issuecomment-144776514>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by vlasovskikh** [comment]
I've updated packaging files for publishing typing==3.5.0 on PyPI. Please review #158.

**Comment by ambv** [comment]
Thanks, Andrey! You can push to PyPI.

**Comment by vlasovskikh** [comment]
@ambv Thanks for the review. I've published 3.5.0 on PyPI.

**Comment by agronholm** [comment]
Thanks!
