### ISSUE TITLE
Alternative Specialization Syntax of Callable

### ISSUE THREAD

**Issue by DRayX** [ambv/typehinting#152]
The current syntax for specializing callable isn't particularly readable, and doesn't really match up with the other syntaxes as the first argument is a list of types.  One possible alternative would be to specify the arguments with the call operator, and the return type with the square brackets.  Thus Callable(int, str)[bool] would be equivalent to the current Callable[[int, str], bool], Callable(int, str) would be equivalent to the current Callable[[int, str], Any], Callable[bool] would be equivalent to the current Callable[[...], bool], and Callable would be equivalent to the current Callable[[...], Any].  This has the advantage of being more readable, clearly distinguishing arguments, and providing additional future support for keyword arguments.  This syntax could potentially coexist with the existing one if there is more than one argument passed to the getitem call.

**Comment by gvanrossum** [comment]
Hm... I don't think this really improves the situation much. It would still be easy to make mistakes like Callable(bool) instead of Callable[bool]. The only thing I believe we could adopt is plain `Callable` for `Callable[..., Any]`. (This may already be the case because it's an ABC.)
