### ISSUE TITLE
Exporting glob imports from stubs

### ISSUE THREAD

**Issue by o11c** [ambv/typehinting#167]
It turns out that it is often necessary to reexport an entire module under a different name.

This could use glob imports, but that doesn't work in stubs since there is no `from foo import * as *` syntax.

For discussion, see: https://github.com/python/typeshed/pull/21 and specifically https://github.com/o11c/typeshed/commit/d7bf7ebe707071390f4be59e0f62659249ec28dc#commitcomment-14039404

**Comment by JukkaL** [comment]
We can make `from m import *` a special case and export all public names imported that way automatically from a stub. I can't come up with another use case where `from ... import *` in a stub would be that useful. Mypy actually already works like this.

**Comment by gvanrossum** [comment]
OK, this sounds fine. Shall I update the PEP?

On Thu, Oct 29, 2015 at 9:56 PM, Jukka Lehtosalo <notifications@github.com>
wrote:

> We can make from m import * a special case and export all public names
> imported that way automatically from a stub. I can't come up with another
> use case where from ... import * in a stub would be that useful. Mypy
> actually already works like this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ambv/typehinting/issues/167#issuecomment-152415408>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by o11c** [comment]
Also clarify that `from ... import ... as ...` does exports too.

**Comment by gvanrossum** [comment]
Done.
