### ISSUE TITLE
Covariance or contravariance

### ISSUE THREAD

**Issue by gvanrossum** [ambv/typehinting#2]
As Lukasz mentions in NOTES-ambv.txt: "The covariance/contravariance discussion needs to happen at some point."

Reference: http://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)

I haven't fully digested all the viewpoints yet. It seems that mypy stays on the safe side and treats e.g. Set[Employee] and Set[Manager] as distinct types. However, Set[Employee] is acceptable where a Set (without parameter) is expected.

**Comment by gvanrossum** [comment]
@vlasovskikh - I can't completely follow your long message -- either you are basically reiterating the need for mutable containers to use invariance, or your point is too subtle (or longwinded) for me. Regarding the use of ``kind='in' / kind='out'``, I'm not sure that is easier to remember (except perhaps for C# users) -- I've already forgotten which means covariant and which contravariant, and what should we use to specify the default explicitly? Finally, your use of an in-line Var() call feels suspect -- at least in mypy, type variables cannot be used inline (you must declare them in the form ``X = typevar('X')``) and I like that. But I can't tell whether you were using it as a shorthand or as an essential feature?

**Comment by vlasovskikh** [comment]
@gvanrossum I want to stress two points in my message:

1. By default generic types should be **invariant**
2. There should be an ability to use **declaration-site variance** as well as use-site variance

The rest of my message is just an explanation why I feel that those two are important. I didn't see any mentions of declaration-site variance in discussions of typing, so felt that it was necessary to remind about this option in this discussion.

Anything else including `kind='in'/'out'` as opposed to some other notation for specifying variance as well as in-line `Var()` is not important.

**Comment by gvanrossum** [comment]
OK, I like that generic types should default to invariant.

(However, Tuple and Callable have different rules -- see the theory article, which is now https://www.python.org/dev/peps/pep-0483/. Tuple. being immutable, is covariant -- Callable is covariant in the return type, but contravariant in the arguments. I doubt this is controversial.)

For now I'll take your word on declaration-site variance vs. use-site variance; once I think I understand it I'll let you know what I think of it. :-)

**Comment by vlasovskikh** [comment]
@gvanrossum That makes perfect sense for tuple and callable types.

**Comment by gvanrossum** [comment]
I found a good discussion of declaration-site variance on Wikipedia: http://en.wikipedia.org/wiki/Covariance_and_contravariance_%28computer_science%29#Declaration-site_variance_annotations

Let me summarize it in my own words:

- With declaration-site variance, you state in the interface definition which of the type variables are co- or contravariant (by default they are invariant). For a sound type system, the type checker must verify that covariant variables are not used as method argument types, and contravariant variables are not used as return types.  This exists in C#, Scala, OCaml.
- Use-site variance, known as wildcards in Java, lets the user override the variance when they declare the type of a variable, e.g. as `List<? extends Animal> animals;`. (This is the syntax that Norvig and Bloch said is too complicated.)

If we choose declaration-site variance, there is an opportunity here for a "cute" notation borrowed from Scala and OCaml: +T for using T covariantly, -T for using it contravariantly (C# uses out/in, but the latter is a bit problematic because it is a Python keyword). This is syntactically valid Python, and easy to implement in the runtime typing.py that I am developing, by overloading __pos__ and __neg__ on the TypeVar class. Example:
```
class Node(Generic[+T]):
   def add_left(self, node: T):
       self.left = node
```
(TBD: Add usage example with Employee/Manager, check with vlasovskikh's comment.)

**Comment by gvanrossum** [comment]
OK, I think I've got it right, and your `List[TypeVar('T', Employee, kind='out')]` is similar to Java's `List<? extends Employee>`, right? And your recommendation is just not to go there at all.

Using my "cute" spelling idea, perhaps we could replace your
```
T = TypeVar('T', kind='out')
```
with
```
T = +TypeVar('T')
```
(This goes against the rule that a `TypeVar()` expression must be assigned to a variable with the same name, but perhaps we could relax that just enough to allow unary `+` and `-`. Then again it's perhaps too cute. But then again somebody who doesn't get `+TypeVar(...)` probably also doesn't get `TypeVar(..., kind='out')`.)

I'm not sure what Jukka thinks, and we'll have to see how this works out in a larger practice trial (i.e. Python 3.5 :-) but so far I like it.

Apart from how to spell co/contravariant type variables (and whether that should be part of the variable declaration or part of the class definition) I also think we need to discuss bounded type variables in general, but I think that can be done separate from the co/contravariant discussion. (Maybe in #1.)

**Comment by vlasovskikh** [comment]
@gvanrossum That's right. The `+` and `-` syntax is nice, but IMHO is equally hard to get and remember as `kind='in' / 'out'`, since the problem of variance is hard in itself.

I should note that declaration-site variance and use-site variance can co-exist in a language. Maybe in order to simplify things we could use only declaration-site variance.

Here is an example of declaration-site variance vs use-site variance.

Given a hierarchy of `Employee` classes (`Manager` and `Engineer` are `Employee`), in order to define the `best_empoyee` function we can either:

* Use a covariant type for the `employees` argument (such as immutable `Iterable[T]` or `Sequence[T]` ABC types):

```python
T = TypeVar('T'): ...

class Iterable[+T]: ...

def best_employee(employees: Iterable[Employee]) -> Employee:
    return max(employees, key=evaluate)
```

* Or use a concrete mutable invariant `List` type, but change its variance at the use site:

```python
E = TypeVar('E', Employee)

def best_employee(employees: List[+E]) -> E:
    return max(employees, key=evaluate)
```

In this case having covariant `Iterable` and `Sequence` superclasses for `List` feels natural. In general though using declaration-site variance only would require introducing new classes with covariant subsets of methods of invariant types only for making the type checker happy. But again, it's a pretty rare case.

**Comment by gvanrossum** [comment]
OK, that's very clear, and I am beginning to understand what the 39% quoted at http://en.wikipedia.org/wiki/Covariance_and_contravariance_%28computer_science%29#Comparing_Declaration-site_and_Use-site_annotations refers to. I also now understand what they mean with "the Scala Collections library defines three separate interfaces for classes which employ covariance".

I'd love some input from Jukka on this issue (summary: whether to support only declaration-site variance declarations (first bullet), or also use-site variance declarations (second bullet); and what you think of the +T/-T syntax instead of (or as a shorthand for) kind='out'/'in' in the TypeVar() call. Also, what "e = TypeVar('E', Employee)" should mean (without the variance declaration).

**Comment by JukkaL** [comment]
My vote goes to only having declaration-site variance. Many uses of wildcard types as in Java programs (use-site variance) could probably be replaced by using just type variables or using `Any`, even if we can't use declaration-site variance to represent them. For example, consider this example using Java-like syntax:

```
def f(x: List[? extends object]) -> None: ...
```

We can use a type variable to achieve a similar effect:

```
T = TypeVar('T')
def f(x: List[T]) -> None: ...
```

We could also rewrite it using `Any`, at the cost of less effective type checking:

```
def f(x: List[Any]) -> None: ...
```

I looked at this some years ago and it seemed that wildcard types were rarely used in interesting ways, but they may be more widely used in recent Java code.

**Comment by gvanrossum** [comment]
SGTM!

On Wednesday, January 14, 2015, Jukka Lehtosalo <notifications@github.com>
wrote:

> My vote goes to only having declaration-site variance. Many uses of
> wildcard types as in Java programs (use-site variance) could probably be
> replaced by using just type variables or using Any, even if we can't use
> declaration-site variance to represent them. For example, consider this
> example using Java-like syntax:
>
> def f(x: List[? extends object]) -> None: ...
>
> We can use a type variable to achieve a similar effect:
>
> T = TypeVar('T')
> def f(x: List[T]) -> None: ...
>
> We could also rewrite it using Any, at the cost of less effective type
> checking:
>
> def f(x: List[Any]) -> None: ...
>
> I looked at this some years ago and it seemed that wildcard types were
> rarely used in interesting ways, but they may be more widely used in recent
> Java code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ambv/typehinting/issues/2#issuecomment-70043282>.
>


-- 
--Guido van Rossum (on iPad)

**Comment by vlasovskikh** [comment]
@JukkaL Your second example is not equivalent to your first example if we consider `List` to be invariant, not covariant. With declaration-site variance only and invariant `List` you have to introduce covariant ABC superclasses of `List` such as `class Iterable(Generic[+TypeVar('T')]): ...` or just use `List[Any]` or `List` (BTW are those equivalent now?).

**Comment by gvanrossum** [comment]
This is now the most important issue left to decide. It's pretty complex (I always get a headache thinking about this stuff) and I don't really like the `TypeVar('T', kind='in')` syntax, but let's call that a strawman. I checked in some code to typing.py just now (https://github.com/ambv/typehinting/commit/9a434e65dc8a4747d07e0b467a457666406c0d4c) that implements this syntax and passes some simple test cases (I had to fix a bunch of semi-unrelated things that were broken too). I will next try to do a write-up of how I think this should work in the type checker, and why, and post it as the next comment here (unless someone else beats me to it).

**Comment by gvanrossum** [comment]
I wrote something up here: https://github.com/ambv/typehinting/blob/master/VARIANCE.rst

**Comment by gvanrossum** [comment]
FWIW, I think I got in/out mixed up. According to the wikipedia covariant is 'out' (or +) and invariant is 'in' (or -).

**Comment by gvanrossum** [comment]
I can't sleep. :-)

I fixed this in VARIANCE.rst and typing.py. But my real proposal is to drop `kind=('in'|'out')` and instead add separate keyword args `covariant=True` or `contravariant=True`. (Then we can set both if we add bivariance, which is mentioned in the Wikipedia article too. :-)

**Comment by JukkaL** [comment]
@gvanrossum That sounds reasonable -- it has the benefit that anybody can easily google what the technical terms mean, and even though the terms *are* technical, they are pretty widely used with a generally agreed on meaning.

**Comment by NYKevin** [comment]
How would this interact with constraints?  IIUC, the current proposal does something like this:

    T = TypeVar('T', covariant=True)

    class Project(Generic[T]):
        pass

    assert issubclass(Project[Manager], Project[Employee])

But consider:

    T = TypeVar('T', Employee, covariant=True)

    class Project(Generic[T]):
        def __init__(self, leader):
            self.leader = leader  # type: T
            leader.employee_method()

Is this legal?  Do we need to cast `leader` to `Employee`?  Or does `T` just get reduced to `Employee` since it only has one constraint?  More generally, how do we indicate that "`T` is always (must always be) compatible with `Employee`" while preserving generic functionality?

**Comment by gvanrossum** [comment]
We now have agreement on this (we're going to use covariant=True/contravariant=True) and typing.py already implements this, but we still need to update the PEP.

@NYKevin: This is not what constraint arguments to type variables are meant for. You should just use Employee instead of a type variable.
