### ISSUE TITLE
Annotating namedtuples item types

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#21]
There should be a way of annotating the item types of named tuples. Here is my suggested syntax:

```python
X = namedtuple('X', ['a', 'b']) # type: (int, str)
```

The type of `a` would be `int` and the type of `b` would be `str`.

**Comment by ambv** [comment]
Typing namedtuples is a good idea.
```X = NamedTuple('X', [('a', int), ('b', str)])``` is the obvious solution here but the syntax is punctuation heavy. Be sure to support the alternative namedtuple syntax that was ```X = namedtuple('x', 'a b')```. Then you can just do ```X = NamedTuple('X', 'a:int, b:str')```.

**Comment by gvanrossum** [comment]
Jukka has just implemented this for mypy. See
https://github.com/JukkaL/typing/issues/7#issuecomment-68984316 .

(Hm, we have too many repos with issue trackers where we have these
discussions. Let's try to move discussions about what things should look
like to the typehinting repo.)

On Tue, Jan 6, 2015 at 11:58 PM, Łukasz Langa <notifications@github.com>
wrote:

> Typing namedtuples is a good idea.
> X = NamedTuple('X', [('a', int), ('b', str)]) is the obvious solution
> here but the syntax is punctuation heavy. Be sure to support the
> alternative namedtuple syntax that was X = namedtuple('x', 'a b'). Then
> you can just do X = NamedTuple('X', 'a:int, b:str').
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ambv/typehinting/issues/21#issuecomment-68989563>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by ambv** [comment]
Agreed to keep discussions in one place. Context-switching between the repos slows us down.

**Comment by gvanrossum** [comment]
This is also implemented in my typing.py.

**Comment by kirbyfan64** [comment]
I'm late to this discussion...but, wasn't there recently a discussion on making `dict`s in CPython ordered by default like PyPy does? If that were to happen, could the the dict-based syntax for namedtuples be supported?

**Comment by gvanrossum** [comment]
Yes, but that's a big if -- I don't know who's actually working on that. If dicts become ordered we can support that -- but even so, I'd like to support the list-of-tuples form for compatibility with Python 3.2-3.4.

**Comment by gvanrossum** [comment]
Closing, it's now also described in the PEP.

**Comment by gvanrossum** [comment]
Oops.
