### ISSUE TITLE
Other uses of annotations

### ISSUE THREAD

**Issue by mvitousek** [ambv/typehinting#26]
Currently the proposal suggests a dictionary-based syntax for allowing the arbitrary annotations currently used in Python 3 to coexist with type annotations (https://github.com/ambv/typehinting/blob/master/pep-NNNN.txt#L194):

    def notify_by_email(employees: {'type': List[Employee], 'min_size': 1, 'max_size': 100}): ...

This meshes well with existing usage if the existing non-type annotation is already a dictionary, but if it's some other kind of value it forces additional refactoring. Maybe instead, `typing` could provide a `TaggedType` or similar class, which cleanly separates type information from other information that the programmer wants in their annotations:

    def notify_by_email(employees: TaggedType(List[Employee], {'min_size': 1, 'max_size': 100}): ...
    or
    def notify_by_email(employees: TaggedType(List[Employee], 'list of employees to be notified')): ...
    
The first argument is always a type, and the second argument is any arbitrary value.

This would also free up dictionaries for possibly representing structural types/protocols (see #11).

**Comment by ambv** [comment]
The decorator idea to turn off the checker is a good one.

**Comment by gvanrossum** [comment]
Let's do a decorator in typing.py to silence the static checker. It should
work for classes and functions/methods.

Let's not do a decorator to add annotations (I think the use cases would be
too uncommon).

Proposal for the name: @no_type_check or @skip_type_check.

On Wed, Jan 7, 2015 at 12:11 AM, Łukasz Langa <notifications@github.com>
wrote:

> The decorator idea to turn off the checker is a good one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ambv/typehinting/issues/26#issuecomment-68990494>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by ambv** [comment]
@gvanrossum, agreed with just adding the silencing decorator.

Bike shedding for a second, you decide. Skip underscores maybe?

1. @classmethod, @staticmethod, @contextmanager, lots of single word ones like @asyncio.coroutine.
2. Counter examples: @lru_cache, @total_ordering, etc.

**Comment by gvanrossum** [comment]
Let's do `@no_type_checks`. (Or, more verbose, `@typing.no_type_checks`.)

We may still have a comment too (I'm undecided on that, but comments are not ruled out).

**Comment by ambv** [comment]
Fixed in e2e6fc4 (comment named as "type: ignore" for now).

**Comment by JukkaL** [comment]
Added mypy issue: https://github.com/JukkaL/mypy/issues/557

**Comment by gvanrossum** [comment]
Update: it should be `@no_type_check` and `@no_type_check_decorator` as was chosen for the PEP and in some other discussion (can't find the issue right now).
