### ISSUE TITLE
Add type for variable-length, uniform tuples

### ISSUE THREAD

**Issue by gvanrossum** [ambv/typehinting#30]
See also https://github.com/JukkaL/typing/issues/6.

Some ideas:
- Tuple[int, ...]
- Sequence[int]

**Comment by gvanrossum** [comment]
It was pointed out on python-ideas that the language about this in the PEP is somewhat ambiguous, e.g. `Tuple[t1, ..., t2]` or `Tuple[..., t1]` should be clearly ruled out.

**Comment by gvanrossum** [comment]
Also, does the empty tuple match `Tuple[int, ...]`?

**Comment by JukkaL** [comment]
I think an empty tuple should match `Tuple[int, ...]`.

**Comment by gvanrossum** [comment]
This is decided and written up in the PEP: the syntax is `Tuple[t1, ...]` (the `...` are a literal ellipsis).
