### ISSUE TITLE
Should the PEP retain the list of comparable projects?

### ISSUE THREAD

**Issue by gvanrossum** [ambv/typehinting#31]
I'm thinking that the PEP will be long enough without also having to contain a survey of how other languages or frameworks approach similar issues. So perhaps we can move your (admirable, and useful!) survey somewhere else? Maybe a separate informational PEP that we can reference, so we won't have to worry about where to host it.

**Comment by ambv** [comment]
Agreed, will make it a separate informational document and just reference it a single sentence. The reasoning behind this survey is so that the reader knows that we considered those alternatives.

**Comment by ambv** [comment]
By the way, this will enable us to take suggestions from the general public on what else should we include, if anything significant is missing.

**Comment by gvanrossum** [comment]
The literature review is now in PEP 482: https://www.python.org/dev/peps/pep-0482/

**Comment by vlasovskikh** [comment]
PyCharm has been providing a way to specify and check types for about four years. [The type system](https://github.com/JetBrains/python-skeletons#types) suggested by PyCharm grew from simple class types to tuple types, generic types, function types, etc. based on feedback of many users who shared their experience of using type hints in their code. It could be mentioned in the literature review PEP 482.

**Comment by gvanrossum** [comment]
Thanks, added (using almost literally what you wrote here :-).
