### ISSUE TITLE
Find a better place to host the "theory of type hinting" article

### ISSUE THREAD

**Issue by gvanrossum** [ambv/typehinting#32]
Maybe an informational PEP? This is about https://quip.com/r69HA9GhGa7J .

**Comment by ambv** [comment]
If you want to reference it in "Type Hints" PEP, putting it in a separate informational PEP seems natural. Just like #31.

I think the distutils changes were precedent in splitting one project into multiple PEPs. In this case it's less controversial since both #31 and #32 will be informative.

**Comment by gvanrossum** [comment]
OK, let's do that. I propose that we order them as follows:
- N: literature overview
- N+1: theory
- N+2: specification

**Comment by gvanrossum** [comment]
OK, I committed stubs for three PEPs: 482 (literature), 483 (theory), 484 (spec). The latter two are empty except for temporary links to the source material. I copied the literature section into 482. It will be a few minutes before these appear on python.org.

**Comment by ambv** [comment]
I do have commit privileges to peps, yes.
