### ISSUE TITLE
Support Any(val)?

### ISSUE THREAD

**Issue by gvanrossum** [ambv/typehinting#33]
I just noticed that mypy's typing.py says that Any can be used to cast a value to type Any. E.g.
```
x = 42  # type: int
y = Any(x)
y.append(42)  # No error
```
Do we want/need this? What other notation could be used that we already support?

**Comment by JukkaL** [comment]
Mypy understands `Any(x)` as an alternative syntax for `cast(Any, x)`. It's just a small convenience feature and not essential.

**Comment by gvanrossum** [comment]
Let's not have that in the PEP.

**Comment by ambv** [comment]
OK.

**Comment by JukkaL** [comment]
Added mypy issue for removing support for `Any(x)`: https://github.com/JukkaL/mypy/issues/558
