### ISSUE TITLE
Description of Any in PEP does not match philosophy document

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#38]
The PEP say this about `Any`:

A special kind of union type is ``Any``, a class that responds
``True`` to ``issubclass`` of any class. This lets the user
explicitly state that there are no constraints on the type of a
specific argument or return value.

But `Any` is actually quite different from a union type (see discussion of gradual typing in Guido's philosophy document), so it should be introduced as a separate concept. The above makes `Any` sound equivalent to `object`, which is not the case.

**Comment by gvanrossum** [comment]
Moving to README.rst.
