### ISSUE TITLE
Describe how to define generic classes

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#40]
Currently the PEP doesn't seem to mention how to define generic classes. The PEP should explain it.

Mypy uses this approach:

```
from typing import TypeVar, Generic, Undefined

T = TypeVar('T')

class MyBucket(Generic[T]):
    def __init__(self, value: T) -> None:
        self.value = value

b = Undefined(MyBucket[int])
b = MyBucket(1)
```

**Comment by JukkaL** [comment]
Added section 'User-defined generic types'.

**Comment by methane** [comment]
I read the section and I have question.
How instance of generic type is inferenced?

```python
 T = TypeVar('T')

  class LoggedVar(Generic[T]):
      def __init__(self, value: T, name: str, logger: Logger) -> None:
          self.name = name
          self.logger = logger
          self.value = value


v1 = LoggedVar(3, "foo", logger)
# Is v1 LoggedVar[Any] or LoggedVar[int]?

v2 = LoggedVar[int](3, "bar", logger)
# Is this possible?  type(v2) is LoggedVar or LoggedVar[int] ?
```

**Comment by gvanrossum** [comment]
mypy correctly infers the type if v1 as `LoggedVar[int]`, but at runtime the class will just be `LoggedVar` (which means the same as `LoggedVar[Any]`. The second form is also possible; in that case the runtime class will be `LoggedVar[int]`.
