### ISSUE TITLE
Type comment and multiple assignment

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#50]
Mypy supports these syntax variants for declaring the types of multiple variables:

```
a, b = 1, 'x' # type: (int, str)
# or
c, d = 1, 'x' # type: int, str
# or
e, f = Undefined, Undefined # type: int, str
# or
g, h = Undefined(int), Undefined(str)
```

I don't think that this case is mentioned in the PEP draft. 

An alternative would be use `Tuple[...]` for this, but I think that this is a bit confusing, since no variables actually will have a tuple type:

```
a, b = 1, 'x' # type: Tuple[int, str]
```

**Comment by gvanrossum** [comment]
I like what mypy does here. Let's add it to the PEP. (Hopefully you can add it yourself?)

**Comment by JukkaL** [comment]
I'll update the PEP (probably later this week).

**Comment by markshannon** [comment]
Now that `Undefined` has been dropped, I think this just leaves the first two options.

**Comment by JukkaL** [comment]
The first two options are already mentioned in the PEP.
