### ISSUE TITLE
The PEP should list some rejected alternative syntaxes and explain why

### ISSUE THREAD

**Issue by gvanrossum** [ambv/typehinting#55]
On the list, Daniel Fetchinson wrote:

It looks like type hinting as a feature is applauded by everyone but
the actual syntax/implementation is polarizing. Could we have a
section in the PEP listing all alternative sytax/implementations with
pros and cons? Stuff like:

1. Stub files

2. property-style type hinting, e.g.:

    @typehints( arg1: int, arg2: str, returns: str )
    def func( arg1, arg2 )
        return 'hello'

3. docstrings, e.g.:

    def func( arg1, arg2 ):
        """type hints: arg1: int, arg2: str, returns: str"""
        return 'hello'

4. Cobra-inspired type hints, e.g.:

    def func( arg1, arg2 ):
        requires:
            isinstance( arg1, int )
            isinstance( arg2, str )
        returns:
            str

**Comment by Rosuav** [comment]
Wouldn't PEP 3107 be one of the strongest arguments here? "We have function annotations, let's use them"?

Additional alternate syntax to mention: Magic comments.

**Comment by gvanrossum** [comment]
Well, the point is that there was a lot of opposition to using PEP 3107... Which needs to be addressed somehow (even if it's just explaining why all of the proposed compromises and alternatives are no good).

**Comment by fetchinson** [comment]
Yes, this would calm (most of) the opposition voices I think. The main concern is that while

def greeting(name: str) -> str:
    return 'Hello ' + name

looks nice, intuitive and noise free, the whole thing can easily get out of hand by (example from the pep):

def async_query(on_success: Callable[[int], None], on_error: Callable[[int, Exception], None]):
    .....

and similar, which do look a bit noisy without the option to visually discard type hinting. 

Another concern is that comments and doc strings were rejected as the avenue for type hinting but nevertheless the pep uses comment based info by the

# type: ignore

idiom. If type hinting shouldn't be in comments, why is it okay to have the above information in comments?

**Comment by fetchinson** [comment]
It would be great if the official position on this principle would be clarified: "source code is by far more often read by humans than type checking and other tools" another variant: "it is by far more important for source code to be humanly readable than readable by various tools".

If we have to choose between "human readable" or "tool readable" I think we should err on the side of humans.

**Comment by lazytype** [comment]
Using newlines often helps readability
```
def async_query(
    on_success: Callable[[int], None], 
    on_error: Callable[[int, Exception], None],
):
```

**Comment by gvanrossum** [comment]
Moving this to README.rst.

**Comment by gvanrossum** [comment]
Sphinx `:param` notation also needs to be discussed.

**Comment by aroberge** [comment]
For completeness, would you consider adding to the list of considered alternative using a code block introduced by a keyword? http://aroberge.blogspot.ca/2015/01/type-hinting-in-python-focus-on.html

While it looks somewhat similar to the cobra-inspired syntax, it is not limited to functions.

Since it was never (to my knowledge) discussed anywhere else, I would understand if it were not added to the list of considered alternatives.

**Comment by gvanrossum** [comment]
Yeah, though new syntax is completely out -- it would make it impossible to
backport the module, whereas mypy already works with Python 3.2 and newer.

On Fri, Jan 30, 2015 at 7:41 AM, André Roberge <notifications@github.com>
wrote:

> For completeness, would you consider adding to the list of considered
> alternative using a code block introduced by a keyword?
> http://aroberge.blogspot.ca/2015/01/type-hinting-in-python-focus-on.html
>
> While it looks somewhat similar to the cobra-inspired syntax, it is not
> limited to functions.
>
> Since it was never (to my knowledge) discussed anywhere else, I would
> understand if it were not added to the list of considered alternatives.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ambv/typehinting/issues/55#issuecomment-72220143>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by gvanrossum** [comment]
Also http://aroberge.blogspot.ca/2015/01/type-hinting-in-python-focus-on.html
