### ISSUE TITLE
How to describe the default value for an argument with a type variable type

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#57]
Consider this generic function in a stub:

```
def foo(x: AnyStr, y: AnyStr = ...) -> AnyStr: pass
```

What should we use as the default argument value for `y`? The type of `y` can be `str` or `bytes`, so either literal is not valid. `None` is also not valid (we don't want the type to be `Optional[AnyStr]`). 

Here are some ideas:

* `Undefined`
* `...` (i.e., literal ellipsis)
* `cast(Any, ...)` (a hack)
* `cast(AnyStr, ...)` (another hack)

**Comment by gvanrossum** [comment]
Since it's in a stub, can't you use `@overload`?
```
@overload
def foo(x: AnyStr) -> AnyStr: pass
@overload
def foo(x: AnyStr, y: AnyStr) -> AnyStr: pass
```

**Comment by JukkaL** [comment]
Yeah, that's what I'm currently using -- but I'm specifically trying to avoid `@overload` due to verbosity and maintainability issues.

Another similar case is a callable default argument value, and to a some extent, arguments with non-primitive class types. For example:

```
class A:
    def __init__(self, x: int, y: int, ...) -> None: pass # lot's of arguments

def f(a: A = ...) -> None: pass  # default argument value?
```

This is not a big issue, but it's sometimes annoying.

Here is another workaround (but this could be flagged as an error my a type checker):

```
class A: ...

_a_default = Undefined(A)

def f(a: A = _a_default) -> None: pass
```

Or like this, if we have a type variable type (but again, I'm not sure whether this should be allowed):

```
_default = Undefined(Any)

def f(x: AnyStr, y: AnyStr = _default) -> AnyStr: pass
```

**Comment by gvanrossum** [comment]
I like using plain Undefined for the default.



-- 
--Guido van Rossum (on iPad)

**Comment by vlasovskikh** [comment]
I guess after #81 using `...` looks like the least hacky variant from the above set.

**Comment by JukkaL** [comment]
I agree that `...` would be a reasonable syntax, though the `cast` hack would work equivalently (it'd just be more ugly).
