### ISSUE TITLE
isinstance and issubclass with type variables confusing

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#62]
Extract from the current prototype of typing in this repo:

    For an unconstrained type variable T, isinstance(x, T) is false
    for all x, and similar for issubclass(cls, T).  Example::

      T = TypeVar('T')
      assert not isinstance(42, T)
      assert not issubclass(int, T)

    For a constrained type variable T, isinstance(x, T) is true for
    any x that is an instance of at least one of T's constraints,
    and similar for issubclass(cls, T).  Example::

      AnyStr = TypeVar('AnyStr', str, bytes)
      # AnyStr behaves similar to Union[str, bytes] (but not exactly!)
      assert not isinstance(42, AnyStr)
      assert isinstance('', AnyStr)

This seems inconsistent. In the first case, every type is a valid value for the type variable, so I'd expect `isinstance` to always return `True`, to be consistent with `AnyStr`.

Even then, using `isinstance(x, T)` if `T` is a type variable would likely be a programming error, as I expect that the programmer's intention would be to check againt the runtime value of the type variable, which is not available since types are erased (outside annotations). Example:

```
from typing import TypeVar
T = TypeVar('T')
def check(x: T, o: object) -> bool:
    return isinstance(o, T)

check(1, 1)  # somebody may expect this to be True
check(1, 'x')  # somebody may expect this to be False
```

I suggest that `isinstance` and `issubclass` raise an exception if used with type variable types.

**Comment by JukkaL** [comment]
Okay, I just noticed that `Union` uses `issubclass`. This seems slightly wrong to me with the above definitions for type variables. For example:

```
from typing import AnyStr
def f(s: AnyStr) -> None:
    x = Undefined(Union[AnyStr, str])  # This evaluates to Undefined(AnyStr)
    x = s   # ok
    if isinstance(s, bytes):
         x = 'x'    # AnyStr is bytes here, but x gets a str value
```

The above code should type check okay, but at runtime we have a misleading type in the `Undefined` object. This is a contrived example -- this won't make a practical difference either way, but it feels wrong to me. Maybe `Union` should not simplify type varariables away, unless the same variable is used multiple times?

Also this is probably also wrong:

```
>>> from typing import *
>>> A = TypeVar('A', str, bytes)
>>> Union[A, AnyStr]
~AnyStr
```

`A` and `AnyStr` are independent type variables, and they could have different values, so they should be both preserved in the union, I think.

**Comment by gvanrossum** [comment]
There are all good suggestions. I'm not sure how soon I can implement them.

**Comment by gvanrossum** [comment]
I will get rid of the T.bind() stuff, it's just a distraction. I can make it so that `isinstance(x, T)` always raises; for issubclass() I am running into some issue with how it is used (typing itself fails to import), so I propose to make issubclass(C, T) work using the following definition:
- if T has no constraints, issubclass(C, T) == True
- if T has one or more constraints, issubclass(C, T) == issubclass(C, Union[T.__constraints__])

It's easy to make Union keep all type variables.

I am running into some issues with Match and Pattern, I have to change the way _TypeAlias works (it's only used for these).

**Comment by JukkaL** [comment]
This is what I get right now:

```
>>> T = TypeVar('T')
>>> isinstance(1, T)
False
>>> S = TypeVar('S', int, str)
>>> isinstance(1, S)
True
```

I think `isinstance` should raise an exception in both cases. Anyway, the above behavior doesn't make sense to me.

**Comment by gvanrossum** [comment]
Weird. I thought I fixed that. :-(

**Comment by gvanrossum** [comment]
I suspect you were accidentally testing with an old version. With the latest typing.py I get a clear TypeError for both:
```
$ python3
Python 3.5.0a4+ (default:07b88b324243, May 14 2015, 08:43:15) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing import *
>>> T = TypeVar('T')
>>> isinstance(1,T)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/guido/src/typehinting/prototyping/typing.py", line 429, in __instancecheck__
    raise TypeError("Type variables cannot be used with isinstance().")
TypeError: Type variables cannot be used with isinstance().
>>> S = TypeVar('S', int, str)
>>> isinstance(1, S)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/guido/src/typehinting/prototyping/typing.py", line 429, in __instancecheck__
    raise TypeError("Type variables cannot be used with isinstance().")
TypeError: Type variables cannot be used with isinstance().
>>> 
```

**Comment by JukkaL** [comment]
Ah yes, I was using an old version. I probably shouldn't be testing anything at 10 pm... :-)
