### ISSUE TITLE
Should we allow stub.py or only stub.pyi?

### ISSUE THREAD

**Issue by gvanrossum** [ambv/typehinting#64]
The feedback on python-ideas suggests that people would like to have stubs always use the .pyi extension.

I am beginning to believe this is a good idea -- I know I've been confused between the stub and real version of a file at least twice so far (though both times it was the copy of types.py in the mypy repo, perhaps a special case :-).

**Comment by JukkaL** [comment]
Yeah, using the same extension for both can result in odd situations. I guess the assumption would be that editors and IDEs would eventually learn to recognize the .pyi extension (for syntax highlighting etc.), if it's specified in the PEP.

**Comment by The-Compiler** [comment]
The only benefit I see in reusing `.py` is that editors and other tools don't have to adopt. I think that's a small benefit - editors should easily/quickly be able to do the minimum of just treating `.pyi` the same as `.py` in terms of syntax highlighting, etc.

Other than that, having a different file extension for stub files only makes sense to reduce confusion. Compare to C, and `.c`/`.h` files - even if I have them in a separate folder it'd be weird and confusing to have header files/stubs named `.c` as well.

**Comment by vlasovskikh** [comment]
+1 on .pyi only. It would be more clear for people that they are viewing / editing Python stubs, not the real Python files themselves.

**Comment by gvanrossum** [comment]
Let's do it.
