### ISSUE TITLE
Automatically ignore files without type annotations?

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#69]
Consider the use case where we gradually migrate a large application to optional typing. Preferably, without any type annotations, a type checker should be silent about an unmodified Python program. As we add type annotations, we'd check the annotated parts of code, and eventually the whole program may be type checked.

However, in the starting state with no annotations, how does the type checker know to not type check the module top levels of program files and class bodies (functions won't be type checked because they have no annotations)? To make this more concrete, let's consider an example.

Case 1:

```
x = {}

def get(id):
    return x[id]
```

Should it be okay for a type checker to complain about not being able to infer the type of `x`?

Case 2:

What about this:

```
x = {}

def get(id: str) -> int:
    return x[id]
```

Should the type checker complain now about the type of `x` now?

Case 3:

```
import typing

x = {}

def get(id):
    return x[id]
```

Does the explicit import of `typing` change anything?

Case 4:

Finally, what about this:

```
from typing import Dict

x = {}  # type: Dict[str, int]
y = {}

def get(id: str) -> int:
    return x[id]
```

Here it seems okay to complain about the type of `y`, right? We have no idea about the key and value types.

**Comment by vlasovskikh** [comment]
Shouldn't a type checker safely assume in cases 1-3 that `x: Dict[Any, Any]` and show no warnings? In case 4 `x[id]` is consistent with its type and `y: Dict[Any, Any]` which is OK again.

**Comment by JukkaL** [comment]
There are a few closely related reasons why I don't like automatically falling back to `Any` types, even though technically it would be a simple solution.

1)

I'd like to have the simple property that if you fully annotate all functions and don't use `Any` types anywhere, and silence all type checker complaints, your program will be completely statically typed (i.e., `Any` types don't just appear out of nowhere). If the type checker falls back to `Any` types if it can't infer a type, it's much less obvious where you need to add type annotations -- this may result in people becoming paranoid and annotating every variable "just in case", which would be bad.

2)

In more complex cases it's very difficult to for a programmer to predict when the type checker can't infer an unambiguous type for a variable. If we silently fall back to `Any` types, it will be harder to predict whether a piece of code is statically checked. Of course, we could only fall back to `Any` types in very specific cases, but then this wouldn't solve the original issue and could be fairly ad hoc.

3)

A clever type checker can infer the type of a variable even if it's initialized using `x = {}`, at least in simple cases. For example:

```
x = {}
for i in range(5):
    x[i] = i * i
```

We could easily teach a type checker to infer the type of `x` as `Dict[int, int]` for the above example, but it would be difficult to make this work correctly in general, as sometimes the type may be ambiguous, or it would require non-local context (etc.). Similar to above, if we silently fall back to `Any` types, the type checker becomes hard to predict, and people may just be defensive and annotate everything, which would be counter-productive.

**Comment by JukkaL** [comment]
One option would be to automatically fall back to `Any` types if type inference fails, but we'd also support a 'strict' type checking mode where this wouldn't happen. In this mode we'd also give warnings for missing function type annotations.

Potential syntax:

```
# type: strict

from typing import Any

x = {}   # error, can't infer type of x (would be okay in default mode)

def f(x):  # error, missing annotation (would be okay in default mode)
    return 1

def f(x: Any) -> Any:   # explicit Any types are always okay
    return 2
```

**Comment by JukkaL** [comment]
We discussed this with Andrey and Mark and we think that this should be left to be decided by each tool separately. 

Every tool has different needs and it probably makes sense to allow tools to iterate on this and figure out a good approach.

**Comment by gvanrossum** [comment]
So can we close this as wontfix? I'm adding that label for now.

**Comment by gvanrossum** [comment]
Please close unless you think there's still something to do.
