### ISSUE TITLE
# type: comment indentation

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#70]
In Python, comments don't affect block indentation. This code is fine:

```
  # foo
x = 1
     # bar
if x:
  # zar
    print(x)
```

Should `# type:` comments be similar? This is not specified in the PEP right now.

Case 1:

Should this be okay?

```
    # type: ignore
x = 1 + 'x'   # ignore error
```

Case 2:

Should this be a valid variable annotation?

```
x = <... long expression ...>
          # type: int
y = 2
```

Mypy supports case 2, and I'm currently working on `# type: ignore` comments. My initial attempt checked the indentation levels, but I'm now leaning towards not caring about the indentation of any `# type:` comments, similar to how Python treats ordinary comments.

**Comment by gvanrossum** [comment]
Hm... When we're giving comments a meaning we might as well insist that they are properly indented.

Separately, for case 2, I'm confused whether the following should set the type for x or for y:
```
x = ...
# type: ...
y = ...
```
Especially since the plan for `# type: ignore` is that it affects the code after it, it would be a bit surprising if this example set the type for x.

**Comment by JukkaL** [comment]
Requiring consistent indentation sounds reasonable. Maybe we should only allow `# type: t` (for `t` != `ignore`) on a non-empty line? This would then be invalid:

```
x = ...
# type: int     # Sorry, not allowed
y = ...
```

Or do you think that it should declare the type of `y`?

**Comment by gvanrossum** [comment]
No, I agree that that should be illegal.

On Monday, March 30, 2015, Jukka Lehtosalo <notifications@github.com> wrote:

> Requiring consistent indentation sounds reasonable. Maybe we should only
> allow # type: t (for t != ignore) on a non-empty line? This would then be
> invalid:
>
> x = ...
> # type: int     # Sorry, not allowed
> y = ...
>
> Or do you think that it should declare the type of y?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ambv/typehinting/issues/70#issuecomment-87942081>.
>


-- 
--Guido van Rossum (on iPad)

**Comment by methane** [comment]
Is this OK?
```
for x in xs:  # type: int
```

I feel this is more readable...
```
# type x: int
for x in xs:
```

**Comment by gvanrossum** [comment]
Shouldn't the type of x always be determined by the type of xs?

**Comment by ceridwen** [comment]
+1 for type-checker comments with enforced indentation.  Also, the tighter the restrictions on type comments now, the easier it will be to refactor them automatically if and when there are grammar changes.

**Comment by methane** [comment]
@gvanrossum xs may be any expression.

```python
# Django
for entry in Entry.objects.filter(author='foo').all():
    # type entry: Entry

# SQLAlchemy
for entry in session.query(Entry).filter_by(author='foo'):
    # type entry: Entry
```

I want IDE know type of entry for code completion and static checking.

**Comment by gvanrossum** [comment]
@methane Can you open a separate issue for that? It's not directly related to the indentation question.

**Comment by methane** [comment]
Done (#73).
I'm sorry about O/T posts.

**Comment by vlasovskikh** [comment]
I've added a more precise description of type comment locations to the PEP.
