### ISSUE TITLE
We need a type for generators

### ISSUE THREAD

**Issue by gvanrossum** [ambv/typehinting#76]
The type for generators should also take into account the type of the argument to send() and the return type.

**Comment by vlasovskikh** [comment]
I've added the `Generator` type to typing.py and the PEP.

**Comment by vlasovskikh** [comment]
By the way, `Generator` is a good example of contravariance.

**Comment by gvanrossum** [comment]
Can you add an explanation of Generator to the PEP? It's not in collections.abc, so it needs more explanation than those types that just enhance collection ABCs.

Also, I think there's a third type that parametrizes a generator: the type of the generator's *return value* (since Python 3.3, generators can return a value, and to access that you use `x = yield from g()` in the caller).

Finally, I think Generator() should not be allowed to be instantiated. (See code that I added to e.g. Dict to prevent instantiation.)

**Comment by vlasovskikh** [comment]
@gvanrossum Updated typing.py and the PEP accordingly.
