### ISSUE TITLE
The PEP should clarify the status of typing vs. types

### ISSUE THREAD

**Issue by gvanrossum** [ambv/typehinting#8]
Lukasz wrote:

* The remark about removing ``types`` from being mentioned actually
  makes me think we could solve many issues before they arise by
  introducing a short section **The place of the ``typing`` module in
  the standard library** which would explain how the authors intend for
  it to be used and what is its role compared to builtin types,
  ``types``,  ``collections``, and ``collections.abc``.  The worries
  that Guido has about the ``types`` module being ill-suited for type
  hinted are spot on, we should mention that in the document.

**Comment by ambv** [comment]
Ignored this issue for now: don't know yet.

**Comment by gvanrossum** [comment]
Isn't this all pretty clear now? We should just downplay types.py -- it only defines concrete types. But we could easily have a stub for it if mypy has trouble understanding its highly dynamic approach.

**Comment by gvanrossum** [comment]
I think we need no more edits for this topic. `typing` is mentioned exactly once and in an appropriate fashion (types defined there are acceptable). (@Jukka -- is there mypy work needed to implement this?)
