### ISSUE TITLE
Disallow TypeVar with only one constraint

### ISSUE THREAD

**Issue by vlasovskikh** [ambv/typehinting#82]
Types like `TypeVar('T', Foo)` don't make sense since you can always replace them with just `Foo`. Although type vars with the only constraint don't break anything, they look really confusing and send the wrong message about using `TypeVar`. Issue #39 is a good example of this problem.

**Comment by justanr** [comment]
Could it be used like type synonyms in Haskell? Sure, it's a Foo, but you're communicating specifically what kind of Foo it it is.

```haskell
type Address = [Char]
type Message = [Char]

send_email :: Address -> Message -> IO ()
```

which is far more informative than:

```haskell
send_email :: [Char] -> [Char] -> IO ()
```

Yes, technically it's just two strings, but we're getting more information out of the type signature than "just input strings".

**Comment by gvanrossum** [comment]
For that we have already type aliases
```
Address = str
Message = str

def send_email(add: Address, msg: Message):
```

**Comment by theY4Kman** [comment]
I'm not sure I understand this. What if I want to constrain a method such that two parameters are a certain class, but the *exact same* class?

```python
T = TypeVar('T', Model)

def bulk_create(model: Type[T], instances: Sequence[T]):
    pass
```

How could I do this without a single-constraint TypeVar?

**Comment by ilevkivskyi** [comment]
How about
```python
def bulk_create(model: Type[Model], instances: Sequence[Model]):
    pass
```

**Comment by ilevkivskyi** [comment]
Oh, I see, maybe you actually wanted ``T = TypeVar('T', bound=Model)``?

**Comment by theY4Kman** [comment]
Ah, yes, that's exactly what I wanted. My apologies for missing that. Thank you! :)

**Comment by ilevkivskyi** [comment]
> For my understanding, is `TypeVar("T", bound=Union[Foo, Bar])` equivalent to `TypeVar("T", Foo, Bar)`?

No, these are totally different things. Upper bound is what it says -- an upper bound. While type variable with value restrictions can take only _exactly_ a restriction. For example (read PEP 484) passing a subtype of `Foo` will still infer `T = Foo`.

**Comment by untitaker** [comment]
I see, thanks. Here's an example for future reference:

```python
from typing import TypeVar
from typing import Union

class MyInt(int):
    pass

T = TypeVar("T", int, str)
U = TypeVar("U", bound=Union[int, str])

def takes_t(x: T) -> T:
    return x

def takes_u(x: U) -> U:
    return x

a: int = takes_t(42)
b: int = takes_u(42)

c: str = takes_t("hi")
d: str = takes_u("hi")

e: MyInt = takes_t(MyInt())  # Does not typecheck: takes_t returns int
f: MyInt = takes_u(MyInt())  # Typechecks: takes_u returns MyInt
```

**Comment by dumblob** [comment]
Hm, currently ran into this issue:
```python
T = TypeVar( 'T', bound=Any )
```
```
Traceback (most recent call last):
  File "/home/user/del/test.py", line 92, in <module>
    class RvalProxy( T ):
  File "/usr/lib/python3.9/typing.py", line 623, in __init__
    self.__constraints__ = tuple(_type_check(t, msg) for t in constraints)
  File "/usr/lib/python3.9/typing.py", line 623, in <genexpr>
    self.__constraints__ = tuple(_type_check(t, msg) for t in constraints)
  File "/usr/lib/python3.9/typing.py", line 157, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: TypeVar(name, constraint, ...): constraints must be types. Got (~T,).
```
I have the use case as in the comment https://github.com/python/typing/issues/82#issuecomment-299503701 above but for the type `Any`. Any ideas how to circumvent this artificial restriction?

**Comment by hauntsaninja** [comment]
`python3.9 -c 'from typing import Any, TypeVar; T = TypeVar("T", bound=Any)'` works fine for me.

**Comment by Ma233** [comment]
Hi, I just met a situation that may need a TypeVar with only one constraint:

```python
from enum import Enum
from typing import Type

StateEnum = TypeVar("StateEnum", Enum)

class StateMachine:
    def __init__(self, state_enum: Type[StateEnum], initial_state: StateEnum): ...
```

Here I want to annotate that the `initial_state` is an instance of `state_enum` which will be declared later, and `state_enum` is a subclass of `Enum`.

**Comment by gvanrossum** [comment]
@magine, you should use `bound=Enum`.
