### ISSUE TITLE
Don't like how constants are defined

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#86]
The current draft allows a large class of named constants. These global constants are defined as variables that are initialized with a constant expression and *aren't assigned elsewhere in the program*. I object to the latter due to these reasons:

1. Determining which variables get assigned to somewhere in a program is difficult and expensive for a type checker. For example, a type checker should be able to decide not to type check modules that have stubs (it'll only process the stubs). These stubs may hide other implementation modules that assign to some of the variables that would otherwise be understood as constants. Also, some code may modify a "constant" using `setattr` or module dictionary, and these aren't generally seen by a type checker.
2. A programmer can't easily determine which variable is a constant just by reading a module implementation, since the algorithm for detecting constants is inherently non-local.
3. Tests could modify variables intended as constants (to simulate different environments or configurations, for example), and accidentally make them variables, according to the above definition.

Here are some potential changes to fix the issues:

1. Require constants to be all upper case (ugly, I know) except for some built-in constants (or maybe also allow `__foobar__` constants). Don't check for assignments (or check only within the current module), and reject assignments elsewhere in the program. The programmer must use `setattr`, `# type: ignore` or similar to work around if a variable actually isn't meant to be a constant.
2. Introduce a new annotation such as `# type: constant` (ugly, don't really like it).
3. Only support a fixed set of built-in constants (such as `typing.PY2`).

Potential fixes that I don't like:

1. Only consider assignments within the current module when determining whether something is a constant (bad because this would overapproximate the set of constants).

**Comment by pludemann** [comment]
I hesitate to suggest this, but there could be a `# type: constant ...` hint.

**Comment by gvanrossum** [comment]
Jukka, glad you reviewed it. I can't say I like it that much either, but I figured we needed a strawman to shoot down. Let's look at the use cases for constants in a type checker. There are no actual references to 'constant' outside the sections on constants. So why do we need constants at all? I think the predefined constants are defined to support conditionally defined classes or functions. Maybe we don't need user-defined constants? I'll just rip this section out of the PEP (replacing it with something like "there are no user-defined constants") unless you object.

**Comment by pludemann** [comment]
Agree to removing any mention of constants.

From a type-checker point of view, the only thing that's interesting about a constant is its type; if the value changes, that's OK. Detecting a change from another module is very difficult (probably impossible in the general case) and can be caught when type-checking the other module: _This {global,class}-scope variable has changed type and this will probably break type-checking where it's defined._

**Comment by JukkaL** [comment]
Removing user-defined constants from the PEP sounds good to me.
