### ISSUE TITLE
Description of get_type_hints inaccurate

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#87]
From the PEP draft:

> get_type_hints, a utility function to retrieve the type hints from a
  function or method.  Given a function or method object, it returns
  a dict with the same format as ``__annotations__``, but evaluating
  forward references (which are given as string literals) as expressions
  in the context of the original function or method definition.

However, `get_type_hints` actually evaluates the forward references in the context of the caller.

Maybe mention the optional arguments `globalns` and `localns`?

Also, it uses `sys._getframe` which may not exist in all Python implementations. Maybe add a note about this.

**Comment by gvanrossum** [comment]
Actually I think the implementation is wrong. It shouldn't be hard to
extract the function object from the first argument (in most cases,
anyway), and from there the f_globals. The ns arguments are there for cases
where this fails but that's so obscure that I'd rather not document it.

On Thu, Apr 16, 2015 at 10:45 PM, Jukka Lehtosalo <notifications@github.com>
wrote:

> From the PEP draft:
>
> get_type_hints, a utility function to retrieve the type hints from a
> function or method. Given a function or method object, it returns
> a dict with the same format as __annotations__, but evaluating
> forward references (which are given as string literals) as expressions
> in the context of the original function or method definition.
>
> However, get_type_hints actually evaluates the forward references in the
> context of the caller.
>
> Maybe mention the optional arguments globalns and localns?
>
> Also, it uses sys._getframe which may not exist in all Python
> implementations. Maybe add a note about this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ambv/typehinting/issues/87>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by gvanrossum** [comment]
I've made the implementation match the PEP better, and removed the uses of sys._getframe().
