### ISSUE TITLE
Having multiple stub versions targeting the same package version on PyPI

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#88]
Assume I have stubs for frobnicate 1.0 on PyPI. The package is frobnicate-stubs 1.0. I want to update some of the stubs and give more precise types. I can't update the package version number to frobnicate-stubs 1.1 since this would refer to frobnicate version 1.1 (which doesn't exist yet), rather than stubs version 1.1.

Maybe suggest using 1.0.0.1, 1.0.0.2, as the incremental stub versions in a case like the above (i.e., increment the fourth component of the version of the stubs package if the changes are related to stubs only, but refer to the same package version). Not sure if PyPI supports this, though. Alternatively, using 1.0.1, 1.0.2, etc. should usually be fine as well.

**Comment by gvanrossum** [comment]
So you want to have versioning for the stubs themselves, independently from the package (version) to which they apply? That seems excessive. I guess this is because you want to use `pip install -U` to install the newer version of the stubs? I think it's important to make it really clear which part of the version is for the frobnicate package and which part is for the evolution of the stub. Maybe frobnicate-1.0-stub-<version> where <version> can be whatever makes sense for the stub, perhaps just 1, 2, 3 or 1.0, 1.1, 1.2?

**Comment by ambv** [comment]
For backports that I made, I was using the fourth digit to version the backport itself, like https://pypi.python.org/pypi/singledispatch. Sadly, some people were really vocal about this not being PEP 440 compliant so I reverted configparser to three numbers. People are still complaining BTW.

The problem with having the source project version as part of the package name is that it produces excessive packages on PyPI and is not very discoverable (as in: you cannot easily list all available "versions"). You also can't use version constraints ("equal", "greater-or-equal", etc.) with those.

**Comment by gvanrossum** [comment]
OK, then I have no idea what to do here, but I'm sure there are people elsewhere who do (maybe distutils-sig).

**Comment by sffjunkie** [comment]
In PEP 426 metadata 2.0 there's provision for an extension mechanism (extensions are listed in PEP 459) perhaps you could propose a 'python.typehints' extension or something like it. As Guido says distutils-sig and Nick Coghlan specifically should be able to help.

**Comment by gvanrossum** [comment]
I don't think the PEP has to mention this issue.

**Comment by gvanrossum** [comment]
I think this is pretty theoretical at this point. I'm closing bugs that don't look very actionable.
