### ISSUE TITLE
Generator is a protocol, not a type

### ISSUE THREAD

**Issue by scoder** [ambv/typehinting#89]
The latest PEP update introduced a `Generator` type declaration. This needs to be defined and implemented as a protocol check like `Iterable`, not as a type check against `types.GeneratorType`.

**Comment by scoder** [comment]
Also, `Generator` might not be the right name - `Coroutine` seems more appropriate, doesn't it?

**Comment by gvanrossum** [comment]
I think you're right about this being a protocol -- @JukkaL, would this be easy to implement in mypy? (It's easy enough in types.py.)

Regarding the name, I don't think it should be named coroutine. That's a specific use of the thing that is a generator. We've called this a generator for generations. :-)

**Comment by vlasovskikh** [comment]
Since PEP 484 doesn't introduce support for structural typing, `Generator` is defined as a nominal subclass of `GeneratorType`. We could make it an ABC similar to `Iterable`, but it would still require special protocol-like handling in a type checker.

**Comment by scoder** [comment]
https://bugs.python.org/issue24018
-> "add a Generator ABC"

**Comment by gvanrossum** [comment]
Once the CPython patch is committed I will update typing.py. (But it will be somewhat hacky because typing.py itself needs to support 3.2+.)

**Comment by gvanrossum** [comment]
I think this can be closed. When typing.py detects that collections.abc defines Generator, it derives from that, and the subclasshook should take care of things from there. Right?
