### ISSUE TITLE
predefined constants/up to typechecker?

### ISSUE THREAD

**Issue by JimJJewett** [ambv/typehinting#94]
How can the typing module ensure that PY2, PY3, WINDOWS, and POSIX are defined, if it relies on (potentially absent) 3rd party checker implementations to set the values?

**Comment by gvanrossum** [comment]
Not sure I understand. In typing.py it sets PY2 and PY3 based on sys.version, and the other two based on sys.platform. (There was a time when mypy did this differently. Maybe that's still how mypy documents it?)

**Comment by JimJJewett** [comment]
So what typing.py does sounds fine.  Are you expecting mypy to monkeypatch the typing module, or act as though those variables held different values?

I'm looking at the lines 

    "Some predefined Boolean constants are defined in the ``typing`` module" 

vs 

    "It is up to the type checker implementation to define their values, as long as ``PY2 == not PY3`` and ``WINDOWS == not POSIX``."

**Comment by gvanrossum** [comment]
The thing to know here is that when mypy runs it does not read the typing.py implementation -- it has its own stub. In essence mypy is its own execution environment.
