### ISSUE TITLE
What about existing (or bogus) # type: comments?

### ISSUE THREAD

**Issue by JimJJewett** [ambv/typehinting#95]
Is error processing defined, or is that better left to individual implementations?

**Comment by gvanrossum** [comment]
Not defined, but I think "# type: X" should always require "X" to parse correctly and evaluate without errors at the point where the comment occurs.

**Comment by gvanrossum** [comment]
Oh wait. Didn't see the question in the subject. :-) A checker should complain if you have a false positive on the `# type:` pattern. You'll have to fix your source.
