### ISSUE TITLE
Rename "stub files" to "interface files"?  Or even "info files"?  

### ISSUE THREAD

**Issue by JimJJewett** [ambv/typehinting#96]
Either would be consistent with .pyi

I believe interface files is a better description than stub, since they aren't intended to be filled in.

**Comment by gvanrossum** [comment]
Hm, but "interface" much more strongly reminds people of (e.g.) Java interfaces, but we don't want them to be thought of that way. So I think we should stick with stub.

**Comment by yfyf** [comment]
Sorry to chime in from the outside, but I would also recommend renaming them to interface files / modules or signature files / modules. "Stub" reminds me of something like "(auto-generated) code with structure, but no implementation" -- not ideal too and without previous background it was not immediately obvious what their purpose was.

"Interface modules" would also be consistent with the identically named concept in Ocaml (.mli files), which serves a similar purpose to stub files in Python ("describing the type signatures of an interface that should be implemented by a module").  In the end, the stub files _are_ kind of like interface specifications (though, a bit more than that).

**Comment by gvanrossum** [comment]
Guess what. Many type inference systems have facilities to auto-generate
stubs (check out mypy on github, I think it has two). Comparisons to
strictly typed languages like OCaml only turn me off, TBH.

On Thu, Apr 23, 2015 at 12:45 AM, Ignas Vyšniauskas <
notifications@github.com> wrote:

> Sorry to chime in from the outside, but I would also recommend renaming
> them to interface files / modules or signature files / modules. "Stub"
> reminds me of something like "(auto-generated) code with structure, but no
> implementation" -- not ideal too and without previous background it was not
> immediately obvious what their purpose was.
>
> "Interface modules" would also be consistent with the identically named
> concept in Ocaml (.mli files), which serves a similar purpose to stub files
> in Python ("describing the type signatures of an interface that should be
> implemented by a module"). In the end, the stub files *are* kind of like
> interface specifications (though, a bit more than that).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ambv/typehinting/issues/96#issuecomment-95479090>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by JimJJewett** [comment]
I was thinking of the IXxxx interfaces (from Zope?), though I'm not sure that the Java analogy is entirely bad.  With a stub, I tend to assume it that the developer still has to fill it in, but in this case, there is no intent that the stub ever be filled out with a complete body.
