### ISSUE TITLE
Additional use case for stub files

### ISSUE THREAD

**Issue by JimJJewett** [ambv/typehinting#97]
Some of the nightmare signatures are correct, and even desirable in certain circumstances.  They're just too noisy for easy reading.

As long as separate files for the interface are available (and can even be supplied by 3rd parties, such as IDE developers), that seems like a good place to put the extra-verbose annotations.

**Comment by gvanrossum** [comment]
I wonder if in some cases it would make sense to use Any for the arguments (or something simple like `Iterable[Any]`) but specify the return type more carefully. That way the imprecise stubs won't catch type errors on the call site but at least they won't prevent further analysis using the result.

**Comment by JimJJewett** [comment]
There are absolutely cases where it makes sense for the primary source file to annotate only the return type.  Sometimes the type of the parameters seems obvious by the name (or local convention), but the return type would otherwise require reading the function. 

In some of those cases, an IDE might appreciate an interface file that is explicit about the parameter types anyhow, even if that would be noise for the human reader.

**Comment by gvanrossum** [comment]
What's the action item here?
