### ISSUE TITLE
pyi files importable?

### ISSUE THREAD

**Issue by JimJJewett** [ambv/typehinting#98]
Is there a way that the typing module could provide an import hook to automatically merge (or at least find) .pyi files that are side-by-side with the real source, or in an equivalent of site-packages?

**Comment by JimJJewett** [comment]
Note that the later discussion of pip, PYTHONPATH, and shared/typehints/python3.5 (under storing and distributing) suggest something similar, but that is inconsistent with the earlier advice at the top of the stub files section.

**Comment by gvanrossum** [comment]
I don't want to have to do any work related to finding stub files in typing.py. I'm not sure how you read the section on pip etc. as suggesting this -- stubs are for the type checker, not for the runtime. (The idea of storing stubs alongside the implementation is for the type checker's benefit.)

**Comment by JimJJewett** [comment]
I was thinking that IDEs may want access to the complete, precise type specification, even when the author has chosen to use stub interface files instead of including inline type hints.  Right now, it sounds like each such tool has to invent its own way of getting those interface files as data, and its own way of associating those stub Signatures with the real code.

It also sounds like pip may happen to store the data in a semi-conventional location, so that repetitive code may involve opening a flat file from a well-known location.

I would prefer a standard function to do that.  It may well be better off in inspect than in typing, and it may well not work as an import hook, but I would prefer it be available in a standard form.

**Comment by gvanrossum** [comment]
If you can point to an implementation of what you are proposing you can reopen this issue.
